require "rails"
require 'rails/generators'
require 'bundler'
require "teleporter/version"

require "generators/teleport/start"
require "generators/teleport/gemfile"
require "generators/teleport/rspec"
require "generators/teleport/welcome"
require "generators/teleport/capistrano"
require "generators/teleport/bootstrap"
require "generators/teleport/simple_form"
require "generators/teleport/devise"
require "generators/teleport/devise_oauth"
require "generators/teleport/gitignore"
require "generators/teleport/database"
require "generators/teleport/api"
require "generators/teleport/sidekiq"
require "generators/teleport/redactor_rails"
